# Generated by Django 5.1.3 on 2024-12-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_id',
            new_name='payment_id',
        ),
    ]
