# Generated by Django 5.1.3 on 2024-12-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='payment_id',
        ),
    ]
