# Generated by Django 5.1.3 on 2024-12-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_in_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan'),
        ),
    ]
