# Generated by Django 5.1.3 on 2024-12-04 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_plan_duration_months_plan_duration_in_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
